apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: n7mswx2zy-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-0e7de82d01.nkab.p3.openshiftapps.com/rhtap/rhtap-qe:8f258cf7e4782aff4419139ce49976dcd15a6162@sha256:e9cda945137428c8220159ecd3c10a9f1fe777824228715a34d48f833df1abe4
        name: container-image  
